# Generated by Django 3.2.25 on 2025-11-20 03:03

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(db_index=True, max_length=255)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos_alunos/')),
                ('data_nascimento', models.DateField()),
                ('nrBI', models.CharField(help_text='introduza o numero de bilhere de identidade', max_length=30, unique=True)),
                ('escola_dest', models.CharField(max_length=255)),
                ('classe', models.CharField(max_length=25)),
                ('ativo', models.BooleanField(db_index=True, default=True)),
                ('mensalidade', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))])),
                ('email', models.EmailField(blank=True, db_index=True, help_text='Email do aluno e (opcional)', max_length=254, null=True, unique=True, validators=[django.core.validators.EmailValidator(message='Degite um email valido')])),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Encarregado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos_encarregados/')),
                ('telefone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='MZ')),
                ('nrBI', models.CharField(help_text='introduza o numero de bilhere de identidade', max_length=30, unique=True)),
                ('endereco', models.TextField(blank=True, help_text='bairro, Q, N da casa', null=True)),
                ('ativo', models.BooleanField(db_index=True, default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
