# Generated by Django 3.2.25 on 2025-08-12 17:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transporte', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Encarregado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(max_length=20)),
                ('endereco', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(limit_choices_to={'role': 'ENCARREGADO'}, on_delete=django.db.models.deletion.CASCADE, related_name='perfil_encarregado', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('data_nascimento', models.DateField()),
                ('escola_dest', models.CharField(max_length=255)),
                ('classe', models.CharField(max_length=25)),
                ('activo', models.BooleanField(default=True)),
                ('encarregado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Alunos', to='alunos.encarregado')),
                ('rota', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transporte.rota')),
            ],
        ),
    ]
