# Generated by Django 3.2.25 on 2025-11-20 03:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('alunos', '0001_initial'),
        ('transporte', '0001_initial'),
    ]

    operations = [

    ]
