# Generated by Django 3.2.25 on 2025-08-20 20:31

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0002_aluno_mensalidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='email',
            field=models.EmailField(blank=True, db_index=True, help_text='Email do aluno e (opcional)', max_length=254, null=True, validators=[django.core.validators.EmailValidator(message='Degite um email valido')]),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='ativo',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='encarregado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alunos', to='alunos.encarregado'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='mensalidade',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))]),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='nome',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='encarregado',
            name='endereco',
            field=models.TextField(blank=True, help_text='bairro, Q, N da casa', null=True),
        ),
        migrations.AlterField(
            model_name='encarregado',
            name='telefone',
            field=models.CharField(db_index=True, help_text='Numero de telefone com digitos, podemos iniciar com +', max_length=20, validators=[django.core.validators.RegexValidator(message='O numero de telefone deve conter apenas digitos e pode iniciar com +. deve ter 9 digitos', regex='^\\+?\\d{9}$')]),
        ),
    ]
