# Generated by Django 3.2.25 on 2025-08-23 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0003_auto_20250820_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encarregado',
            name='telefone',
            field=models.CharField(max_length=20),
        ),
    ]
