# Generated by Django 3.2.25 on 2025-08-27 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0004_alter_encarregado_telefone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='encarregado',
            field=models.ForeignKey(help_text='YYYY-MM-DD', on_delete=django.db.models.deletion.CASCADE, related_name='alunos', to='alunos.encarregado'),
        ),
    ]
