# Generated by Django 3.2.25 on 2025-09-01 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0005_alter_aluno_encarregado'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='nrBI',
            field=models.CharField(blank=True, help_text='introduza o numero de bilhere de identidade', max_length=30),
        ),
        migrations.AddField(
            model_name='encarregado',
            name='nrBI',
            field=models.CharField(blank=True, help_text='introduza o numero de bilhere de identidade', max_length=30),
        ),
    ]
