# Generated by Django 3.2.25 on 2025-11-02 10:44

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0006_auto_20250901_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='encarregado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alunos', to='alunos.encarregado'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='nrBI',
            field=models.CharField(help_text='introduza o numero de bilhere de identidade', max_length=30),
        ),
        migrations.AlterField(
            model_name='encarregado',
            name='nrBI',
            field=models.CharField(help_text='introduza o numero de bilhere de identidade', max_length=30),
        ),
        migrations.AlterField(
            model_name='encarregado',
            name='telefone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='MZ'),
        ),
    ]
