# Generated by Django 3.2.25 on 2025-11-02 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0007_auto_20251102_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_alunos/'),
        ),
        migrations.AddField(
            model_name='encarregado',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_encarregados/'),
        ),
    ]
