# Generated by Django 3.2.25 on 2025-11-02 15:29

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transporte', '0005_auto_20251020_1926'),
        ('alunos', '0009_alter_encarregado_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='email',
            field=models.EmailField(blank=True, db_index=True, help_text='Email do aluno e (opcional)', max_length=254, null=True, unique=True, validators=[django.core.validators.EmailValidator(message='Degite um email valido')]),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='nrBI',
            field=models.CharField(help_text='introduza o numero de bilhere de identidade', max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='rota',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='alunos', to='transporte.rota'),
        ),
        migrations.AlterField(
            model_name='encarregado',
            name='nrBI',
            field=models.CharField(help_text='introduza o numero de bilhere de identidade', max_length=30, unique=True),
        ),
    ]
