# Generated by Django 3.2.25 on 2025-11-06 00:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('alunos', '0010_auto_20251102_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encarregado',
            name='user',
            field=models.OneToOneField(limit_choices_to=models.Q(('role__nome', 'ENCARREGADO')), on_delete=django.db.models.deletion.CASCADE, related_name='perfil_encarregado', to=settings.AUTH_USER_MODEL),
        ),
    ]
