# Generated by Django 3.2.25 on 2025-11-18 02:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0011_alter_encarregado_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='activo',
        ),
        migrations.AddField(
            model_name='aluno',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='aluno',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 11, 1, 0, 0)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='encarregado',
            name='ativo',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='encarregado',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='encarregado',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 11, 1, 0, 0)),
            preserve_default=False,
        ),
    ]
