# Generated by Django 3.2.25 on 2025-11-20 03:03

import datetime
from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Motorista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', phonenumber_field.modelfields.PhoneNumberField(db_index=True, help_text='O numero de telefone com 9 digitos', max_length=128, region='MZ')),
                ('endereco', models.CharField(blank=True, max_length=200, null=True)),
                ('carta_nr', models.CharField(db_index=True, max_length=50, unique=True)),
                ('validade_da_carta', models.DateField()),
                ('ativo', models.BooleanField(db_index=True, default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(limit_choices_to=models.Q(('role__nome', 'MOTORISTA')), on_delete=django.db.models.deletion.CASCADE, related_name='perfil_motorista', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Motorista',
                'verbose_name_plural': 'Motoristas',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(default='desconhecida', max_length=20)),
                ('modelo', models.CharField(default='desconhecida', max_length=50)),
                ('matricula', models.CharField(db_index=True, help_text='Placa de matricula do veiculo', max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Placa inválida. Ex: ABC-1234 ou ABC-123-XY', regex='^[A-Z]{2,3}-\\d{1,4}(-[A-Z]{1,2})?$')])),
                ('capacidade', models.PositiveIntegerField(help_text='Numero maximo de Passageiros', validators=[django.core.validators.MinValueValidator(1)])),
                ('ativo', models.BooleanField(db_index=True, default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('motorista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='veiculos', to='transporte.motorista')),
            ],
            options={
                'verbose_name': 'Veículo',
                'verbose_name_plural': 'Veículos',
                'ordering': ['matricula'],
            },
        ),
        migrations.CreateModel(
            name='Rota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(db_index=True, max_length=255)),
                ('hora_partida', models.TimeField(default=datetime.time(6, 0))),
                ('hora_chegada', models.TimeField(default=datetime.time(7, 0))),
                ('descricao', models.TextField(blank=True, null=True)),
                ('ativo', models.BooleanField(db_index=True, default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rotas', to='transporte.veiculo')),
            ],
            options={
                'verbose_name': 'Rota',
                'verbose_name_plural': 'Rotas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Encarregado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos_encarregados/')),
                ('telefone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='MZ')),
                ('nrBI', models.CharField(help_text='introduza o numero de bilhere de identidade', max_length=30, unique=True)),
                ('endereco', models.TextField(blank=True, help_text='bairro, Q, N da casa', null=True)),
                ('ativo', models.BooleanField(db_index=True, default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(limit_choices_to=models.Q(('role__nome', 'ENCARREGADO')), on_delete=django.db.models.deletion.CASCADE, related_name='perfil_encarregado_transporte', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(db_index=True, max_length=255)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos_alunos/')),
                ('data_nascimento', models.DateField()),
                ('nrBI', models.CharField(help_text='introduza o numero de bilhere de identidade', max_length=30, unique=True)),
                ('escola_dest', models.CharField(max_length=255)),
                ('classe', models.CharField(max_length=25)),
                ('ativo', models.BooleanField(db_index=True, default=True)),
                ('mensalidade', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))])),
                ('email', models.EmailField(blank=True, db_index=True, help_text='Email do aluno e (opcional)', max_length=254, null=True, unique=True, validators=[django.core.validators.EmailValidator(message='Email invalido')])),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('encarregado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alunos_transporte', to='transporte.encarregado')),
                ('rota', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='alunos_transporte', to='transporte.rota')),
            ],
            options={
                'verbose_name': 'Aluno',
                'verbose_name_plural': 'Alunos',
                'ordering': ['nome'],
            },
        ),
    ]
