# Generated by Django 3.2.25 on 2025-08-14 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transporte', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='motorista',
            name='telefone',
            field=models.CharField(default='sem telefone', max_length=25),
        ),
    ]
