# Generated by Django 3.2.25 on 2025-08-20 20:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transporte', '0002_motorista_telefone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rota',
            options={'ordering': ['nome']},
        ),
        migrations.AddField(
            model_name='motorista',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='rota',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='motorista',
            name='carta_nr',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='motorista',
            name='telefone',
            field=models.CharField(db_index=True, help_text='O numero de telefone com 9 digitos', max_length=25, validators=[django.core.validators.RegexValidator(message='O numero de telefone deve conter apenas digitos e pode iniciar com +. deve 9 digitos', regex='^\\+?\\d{9}$')]),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='capacidade',
            field=models.PositiveIntegerField(help_text='Numero maximo de Passageiros', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='placa_matricula',
            field=models.CharField(db_index=True, max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Placa inválida. Ex: ABC-1234 ou ABC-123-XY', regex='^[A-Z]{2,3}-\\d{1,4}(-[A-Z]{1,2})?$')]),
        ),
    ]
