# Generated by Django 3.2.25 on 2025-09-29 15:50

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transporte', '0003_auto_20250820_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='motorista',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='motorista',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddField(
            model_name='rota',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='rota',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='rota',
            name='veiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rotas', to='transporte.veiculo'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='placa_matricula',
            field=models.CharField(db_index=True, help_text='Placa de matricula do veiculo', max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Placa inválida. Ex: ABC-1234 ou ABC-123-XY', regex='^[A-Z]{2,3}-\\d{1,4}(-[A-Z]{1,2})?$')]),
        ),
    ]
