# Generated by Django 3.2.25 on 2025-10-20 19:26

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transporte', '0004_auto_20250929_1550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='veiculo',
            name='modelo_carro',
        ),
        migrations.RenameField(
            model_name='veiculo',
            old_name='placa_matricula',
            new_name='matricula',
        ),
        migrations.AddField(
            model_name='motorista',
            name='endereco',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='motorista',
            name='nome',
            field=models.CharField(blank=True, help_text='Nome do motorista', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rota',
            name='hora_chegada',
            field=models.TimeField(default=datetime.time(7, 0)),
        ),
        migrations.AddField(
            model_name='rota',
            name='hora_partida',
            field=models.TimeField(default=datetime.time(6, 0)),
        ),
        migrations.AddField(
            model_name='rota',
            name='motorista',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rotas', to='transporte.motorista'),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='marca',
            field=models.CharField(default='desconhecida', max_length=20),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='modelo',
            field=models.CharField(default='desconhecida', max_length=50),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='matricula',
            field=models.CharField(db_index=True, help_text='Placa de matricula do veiculo', max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Placa inválida. Ex: ABC-1234 ou ABC-123-XY', regex='^[A-Z]{2,3}-\\d{1,4}(-[A-Z]{1,2})?$')]),
        ),
    ]
