# Generated by Django 3.2.25 on 2025-11-02 16:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transporte', '0005_auto_20251020_1926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='motorista',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='rota',
            name='motorista',
        ),
        migrations.AlterField(
            model_name='motorista',
            name='carta_nr',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='motorista',
            name='telefone',
            field=phonenumber_field.modelfields.PhoneNumberField(db_index=True, help_text='O numero de telefone com 9 digitos', max_length=128, region='MZ'),
        ),
        migrations.AlterField(
            model_name='motorista',
            name='user',
            field=models.OneToOneField(limit_choices_to=models.Q(('role', 'MOTORISTA')), on_delete=django.db.models.deletion.CASCADE, related_name='perfil_motorista', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='motorista',
            name='validade_da_carta',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='rota',
            name='veiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rotas', to='transporte.veiculo'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='motorista',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='veiculos', to='transporte.motorista'),
        ),
    ]
