# Generated by Django 3.2.25 on 2025-11-09 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transporte', '0007_alter_motorista_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='motorista',
            options={'ordering': ['-criado_em'], 'verbose_name': 'Motorista', 'verbose_name_plural': 'Motoristas'},
        ),
        migrations.AlterModelOptions(
            name='rota',
            options={'ordering': ['nome'], 'verbose_name': 'Rota', 'verbose_name_plural': 'Rotas'},
        ),
        migrations.AlterModelOptions(
            name='veiculo',
            options={'ordering': ['matricula'], 'verbose_name': 'Veículo', 'verbose_name_plural': 'Veículos'},
        ),
        migrations.AlterField(
            model_name='motorista',
            name='ativo',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='rota',
            name='ativo',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='rota',
            name='nome',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='ativo',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
