# Generated by Django 3.2.25 on 2025-08-15 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
