# Generated by Django 3.2.25 on 2025-08-15 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_data_atualizacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='salario',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
