# Generated by Django 3.2.25 on 2025-08-25 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_salario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMINISTRADOR', 'Administrador'), ('FUNCIONARIO', 'Funcionario'), ('MOTORISTA', 'Motorista'), ('ENCARREGADO', 'Encarregado')], max_length=20),
        ),
    ]
