# Generated by Django 3.2.25 on 2025-09-03 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('FUNCIONARIO', 'Funcionario'), ('MOTORISTA', 'Motorista'), ('ENCARREGADO', 'Encarregado')], max_length=20),
        ),
    ]
