# Generated by Django 3.2.25 on 2025-09-03 20:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_user_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='data_atualizacao',
        ),
        migrations.RemoveField(
            model_name='user',
            name='data_criacao',
        ),
        migrations.AddField(
            model_name='user',
            name='apelido',
            field=models.CharField(default='sem apelido', max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined'),
        ),
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nome',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('FUNCIONARIO', 'Funcionario'), ('MOTORISTA', 'Motorista'), ('ENCARREGADO', 'Encarregado')], default='ENCARREGADO', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='salario',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Salário do usuário (se vazio, aplica valor padrão do cargo).', max_digits=10, null=True),
        ),
    ]
