# Generated by Django 3.2.25 on 2025-11-01 08:57

from django.db import migrations, models
import django.db.models.deletion

ROLES_EXISTENTES = {
    "ADMIN": 25000.00,
    "MOTORISTA": 12000.00,
    "FUNCIONARIO": 10000.00,
    "ENCARREGADO": 0.00,  # Adicionado com salário padrão 0
}

def migrate_data_forward(apps, schema_editor):
    """
    Cria instâncias de Cargo e popula o novo campo role_fk nos usuários existentes.
    """
    Cargo = apps.get_model('core', 'Cargo')
    User = apps.get_model('core', 'User')
    db_alias = schema_editor.connection.alias

    # Cria os objetos Cargo a partir dos nomes existentes
    for nome, salario in ROLES_EXISTENTES.items():
        Cargo.objects.using(db_alias).get_or_create(nome=nome, defaults={'salario_padrao': salario})

    # Popula o novo campo ForeignKey (role_fk)
    for user in User.objects.using(db_alias).filter(role__in=ROLES_EXISTENTES.keys()):
        cargo_obj = Cargo.objects.using(db_alias).get(nome=user.role)
        user.role_fk = cargo_obj
        user.save()

def migrate_data_backward(apps, schema_editor):
    """
    (Opcional) Reverte a migração populando o campo de texto antigo.
    """
    User = apps.get_model('core', 'User')
    db_alias = schema_editor.connection.alias

    for user in User.objects.using(db_alias).all():
        if user.role_fk:
            user.role = user.role_fk.nome
            user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20250903_2140'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('salario_padrao', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='role_fk',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.cargo'
            ),
        ),
        migrations.RunPython(migrate_data_forward, migrate_data_backward),
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='role_fk',
            new_name='role',
        ),
    ]
