# Generated by Django 3.2.25 on 2025-11-19 02:01

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('alunos', '0012_auto_20251118_0226'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PAGO', 'Pago'), ('PENDENTE', 'Pendente'), ('ATRASADO', 'Atrasado'), ('PAGO PARCIAL', 'Pago Parcial')], default='PENDENTE', max_length=20)),
                ('data_pagamento', models.DateTimeField(blank=True, null=True)),
                ('descricao', models.CharField(max_length=255)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('data_emissao', models.DateField(default=django.utils.timezone.now)),
                ('data_vencimento', models.DateField()),
                ('obs', models.TextField(blank=True, null=True)),
                ('recibo_gerado', models.BooleanField(default=False)),
                ('email_destinatario', models.EmailField(help_text=' Email do destinatario da fatura', max_length=254)),
            ],
            options={
                'verbose_name_plural': 'Faturas',
                'ordering': ['-data_emissao'],
            },
        ),
        migrations.CreateModel(
            name='Mensalidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PAGO', 'Pago'), ('PENDENTE', 'Pendente'), ('ATRASADO', 'Atrasado'), ('PAGO PARCIAL', 'Pago Parcial')], default='PENDENTE', max_length=20)),
                ('data_pagamento', models.DateTimeField(blank=True, null=True)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('mes_referente', models.DateField(help_text='Mes de referencia')),
                ('data_vencimento', models.DateField()),
                ('data_limite', models.DateField(help_text='O ultimo dia permitido para o pagamento')),
                ('taxa_atraso', models.DecimalField(decimal_places=2, default=0.1, help_text='A taxa de juros incrementa a cada 5 dias(ex:0.10 = 10%)', max_digits=5)),
                ('obs', models.TextField(blank=True, null=True)),
                ('recibo_gerado', models.BooleanField(default=False)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensalidades', to='alunos.aluno')),
            ],
            options={
                'ordering': ['-mes_referente'],
                'unique_together': {('aluno', 'mes_referente')},
            },
        ),
        migrations.CreateModel(
            name='Salario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PAGO', 'Pago'), ('PENDENTE', 'Pendente'), ('ATRASADO', 'Atrasado'), ('PAGO PARCIAL', 'Pago Parcial')], default='PENDENTE', max_length=20)),
                ('data_pagamento', models.DateTimeField(blank=True, null=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mes_referente', models.DateField(max_length=20, verbose_name='Mes de referencia')),
                ('obs', models.TextField(blank=True, null=True)),
                ('recibo_gerado', models.BooleanField(default=False)),
                ('funcionario', models.ForeignKey(limit_choices_to={'role__in': ['FUNCIONARIO', 'MOTORISTA', 'ADMINISTRADOR']}, on_delete=django.db.models.deletion.CASCADE, related_name='salarios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Salario',
                'verbose_name_plural': 'Salarios',
                'ordering': ['-mes_referente'],
            },
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('data_pagamento', models.DateTimeField(default=django.utils.timezone.now)),
                ('metodo_pagamento', models.CharField(choices=[('DINHEIRO', 'Dinheiro'), ('TRANSFERENCIA', 'Transferência'), ('CARTAO', 'Cartão')], default='DINHEIRO', max_length=20)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('mensalidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='financeiro.mensalidade')),
            ],
            options={
                'ordering': ['-data_pagamento'],
            },
        ),
        migrations.CreateModel(
            name='AlertaEnviado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('ATRASO', 'Pagamento em atraso'), ('INICIO', 'Inicio do periodo de pagamento'), ('PENDENTE', 'pagamento pendente'), ('OUTRO', 'Outro')], default='OUTRO', max_length=20)),
                ('email', models.EmailField(help_text='Email usado no envio', max_length=254)),
                ('mensagem', models.TextField()),
                ('enviado_em', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('ENVIADO', 'Enviado'), ('FALHA NO ENVIO', 'Falha no envio'), ('PENDENTE', 'Pendente')], default='ENVIADO', max_length=50)),
                ('alunos', models.ManyToManyField(related_name='alerta_enviados', to='alunos.Aluno')),
                ('encarregado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerta_enviados', to='alunos.encarregado')),
            ],
            options={
                'ordering': ['-enviado_em'],
            },
        ),
    ]
