# Generated by Django 3.2.25 on 2025-08-12 17:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alunos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Salario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mes_referente', models.CharField(max_length=20)),
                ('data_pagamento', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PAGO', 'Pago'), ('PENDENTE', 'Pendente')], default='PENDENTE', max_length=20)),
                ('funcionario', models.ForeignKey(limit_choices_to={'role__in': ['FUNCIONARIO', 'MOTORISTA']}, on_delete=django.db.models.deletion.CASCADE, related_name='salarios', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mes_referente', models.CharField(max_length=20)),
                ('data_pagamento', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PAGO', 'Pago'), ('PENDENTE', 'Pendente')], default='PENDENTE', max_length=20)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamento', to='alunos.aluno')),
            ],
        ),
    ]
