# Generated by Django 3.2.25 on 2025-08-19 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0002_aluno_mensalidade'),
        ('financeiro', '0002_auto_20250815_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamento',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='alunos.aluno'),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='mes_referente',
            field=models.DateField(verbose_name='mes de referencia'),
        ),
        migrations.AlterField(
            model_name='salario',
            name='mes_referente',
            field=models.DateField(verbose_name='Mes de referencia'),
        ),
    ]
