# Generated by Django 3.2.25 on 2025-08-20 20:31

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0003_auto_20250820_2031'),
        ('financeiro', '0004_auto_20250819_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamento',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))]),
        ),
        migrations.AlterUniqueTogether(
            name='pagamento',
            unique_together={('aluno', 'mes_referente')},
        ),
        migrations.CreateModel(
            name='AlertaEnviado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('mensagem', models.TextField()),
                ('enviado_em', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='ENVIADO', max_length=50)),
                ('alunos', models.ManyToManyField(related_name='alerta_enviados', to='alunos.Aluno')),
                ('encarregado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='alunos.encarregado')),
            ],
        ),
    ]
